# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    minimum_pre_commit_version: 2.10.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-added-large-files
    -   id: detect-aws-credentials
    -   id: no-commit-to-branch
        args: [--branch, development, --branch, master, --branch, testing]
    -   id: pretty-format-json
        args: [--autofix]
    - id: check-case-conflict

-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.9

-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    -   id: autoflake
        args: [--in-place, --remove-all-unused-imports,--remove-unused-variable]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black, --filter-files]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

-   repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
    -   id: pylint
        args: [--fail-under=9]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
        verbose: true
        args: [--show-error-codes]
        additional_dependencies: ['types-requests']

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
